language: cpp
cache:
  - pip
  - ccache
  - yarn
  - npm
sudo: required
dist: trusty

os:
  - linux
    # much bug with osx environment
    # TODO(ChunweiYan) support osx in the future
    #- osx

addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - git
      - python
      - python-pip
      - python2.7-dev
      - python-wheel
      - clang-format-3.8
      - ccache
      - npm
      - nodejs

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install brew-pip; fi
  - sudo pip install pre-commit flake8

script:
  - ./travis/check_style.sh
  - ./tests.sh all

notifications:
  email:
    on_success: change
    on_failure: always
